/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DAL.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Windows.lite
 */
public class TelaAutomovel extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAutomovel
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaAutomovel() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAutoEdit = new javax.swing.JButton();
        btnAutoExc = new javax.swing.JButton();
        btnRelAuto = new javax.swing.JButton();
        btnAutoCad = new javax.swing.JButton();
        btnAutoPes = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtRenavam = new javax.swing.JTextField();
        txtFabri = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();

        setTitle("TELA - AUTOMOVEL - FUNÇÃO");

        jLabel1.setText("CODIGO");

        jLabel2.setText("PLACA");

        jLabel3.setText("RENAVAM");

        jLabel4.setText("FABRICANTE");

        jLabel5.setText("MODELO");

        jLabel6.setText("ANO");

        jLabel7.setText("COR");

        btnAutoEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/autoedt.jpg"))); // NOI18N
        btnAutoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoEditActionPerformed(evt);
            }
        });

        btnAutoExc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/autoremov.jpg"))); // NOI18N
        btnAutoExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoExcActionPerformed(evt);
            }
        });

        btnRelAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/211880_printer_icon.png"))); // NOI18N
        btnRelAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelAutoActionPerformed(evt);
            }
        });

        btnAutoCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/autonew.jpg"))); // NOI18N
        btnAutoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoCadActionPerformed(evt);
            }
        });

        btnAutoPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/userPesquisar.png"))); // NOI18N
        btnAutoPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoPesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCor, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtAno)
                            .addComponent(txtModel)
                            .addComponent(txtRenavam)
                            .addComponent(txtFabri)
                            .addComponent(txtCodigo)
                            .addComponent(txtPlaca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnAutoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutoPes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutoEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutoExc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRelAuto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFabri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRelAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAutoCad)
                        .addComponent(btnAutoPes)
                        .addComponent(btnAutoEdit)
                        .addComponent(btnAutoExc)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoCadActionPerformed
        // TODO add your handling code here:
        cadastrar();
        String sql = "INSERT INTO e1_automovel(COD, PLACA, RENAVAM, FABRICANTE, "
                + "MODELO, ANO, COR) VALUES (?,?,?,?,?,?,?)";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());
            pst.setString(2, txtPlaca.getText());
            pst.setString(3, txtRenavam.getText());
            pst.setString(4, txtFabri.getText());
            pst.setString(5, txtModel.getText());
            pst.setString(6, txtAno.getText());
            pst.setString(7, txtCor.getText());
            //System.out.println(pst);

            int resultado = pst.executeUpdate();
            if (resultado == 1) {
                JOptionPane.showMessageDialog(null, "Cadastrado!");

                txtCodigo.setText(null);
                txtPlaca.setText(null);
                txtRenavam.setText(null);
                txtFabri.setText(null);
                txtModel.setText(null);
                txtAno.setText(null);
                txtCor.setText(null);

            } else {
                JOptionPane.showMessageDialog(null, "Não cadastrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAutoCadActionPerformed

    private void btnAutoPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoPesActionPerformed
        // TODO add your handling code here:
        consultar();
        String sql = "SELECT * from e1_automovel WHERE COD=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());

            rs = pst.executeQuery();

            if (rs.next()) {
                txtPlaca.setText(rs.getString("Placa"));
                txtRenavam.setText(rs.getString("Renavam"));
                txtFabri.setText(rs.getString("Fabricante"));
                txtModel.setText(rs.getString("Modelo"));
                txtAno.setText(rs.getString("Ano"));
                txtCor.setText(rs.getString("cor"));

            } else {

                JOptionPane.showMessageDialog(null, "Não Localizado!");
                txtCodigo.setText(null);
                txtPlaca.setText(null);
                txtRenavam.setText(null);
                txtFabri.setText(null);
                txtModel.setText(null);
                txtAno.setText(null);
                txtCor.setText(null);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAutoPesActionPerformed

    private void btnAutoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoEditActionPerformed
        // TODO add your handling code here:
        atualizar();
        String sql = "UPDATE e1_automovel SET PLACA=?, RENAVAM=?, FABRICANTE=?, "
                + "MODELO=?, ANO=?, COR=? where cod=?";

        try {
            pst = conexao.prepareStatement(sql);

            pst.setString(1, txtPlaca.getText());
            pst.setString(2, txtRenavam.getText());
            pst.setString(3, txtFabri.getText());
            pst.setString(4, txtModel.getText());
            pst.setString(5, txtAno.getText());
            pst.setString(6, txtCor.getText());
            pst.setString(7, txtCodigo.getText());
            //System.out.println(pst);

            int atualizado = pst.executeUpdate();
            if (atualizado == 1) {

                JOptionPane.showMessageDialog(null, "Atualizado!");
                txtCodigo.setText(null);
                txtPlaca.setText(null);
                txtRenavam.setText(null);
                txtFabri.setText(null);
                txtModel.setText(null);
                txtAno.setText(null);
                txtCor.setText(null);

            } else {
                JOptionPane.showMessageDialog(null, "Não Atualizado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAutoEditActionPerformed

    private void btnAutoExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoExcActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_btnAutoExcActionPerformed

    private void btnRelAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelAutoActionPerformed
        // TODO add your handling code here:
        RelAutomovel();
    }//GEN-LAST:event_btnRelAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoCad;
    private javax.swing.JButton btnAutoEdit;
    private javax.swing.JButton btnAutoExc;
    private javax.swing.JButton btnAutoPes;
    private javax.swing.JButton btnRelAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtFabri;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRenavam;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void consultar() {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void atualizar() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void remover() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja remover?", "ATENÇÃO!!!", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_NO_OPTION) {
            String sql = "delete from e1_automovel where cod=?";

            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtCodigo.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Removido com sucesso!!!");
                    txtCodigo.setText(null);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }

    private void RelAutomovel() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão", "", JOptionPane.YES_NO_OPTION);
        String caminho = "RelAuto.jasper";
        if (confirma == JOptionPane.YES_NO_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport(caminho, null, conexao);
                JasperViewer.viewReport(print, false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }
}
