/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DAL.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Windows.lite
 */
public class TelaOcorrencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaOcorrencia
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaOcorrencia() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        txtDescr = new javax.swing.JTextField();
        btnOcoEdit = new javax.swing.JButton();
        btnOcoExc = new javax.swing.JButton();
        btnRelOco = new javax.swing.JButton();
        btnOcoCad = new javax.swing.JButton();
        btnOcoPes = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();

        setTitle("TELA - OCORRÊNCIA");

        jLabel1.setText("I.D");

        jLabel2.setText("DATA");

        jLabel3.setText("LOCAL");

        jLabel4.setText("DESCRIÇÃO");

        btnOcoEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/103765_close_user_settings_icon.png"))); // NOI18N
        btnOcoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoEditActionPerformed(evt);
            }
        });

        btnOcoExc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/103763_close_user_remove_icon.png"))); // NOI18N
        btnOcoExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoExcActionPerformed(evt);
            }
        });

        btnRelOco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/211880_printer_icon.png"))); // NOI18N
        btnRelOco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelOcoActionPerformed(evt);
            }
        });

        btnOcoCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/103747_close_add_user_icon.png"))); // NOI18N
        btnOcoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoCadActionPerformed(evt);
            }
        });

        btnOcoPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/825453_magnifying glass_people_search_searchicons_user_icon.png"))); // NOI18N
        btnOcoPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoPesActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnOcoCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcoPes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcoEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOcoExc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRelOco)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOcoCad)
                    .addComponent(btnOcoPes)
                    .addComponent(btnOcoEdit)
                    .addComponent(btnOcoExc)
                    .addComponent(btnRelOco))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOcoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoCadActionPerformed
        // TODO add your handling code here:
        
        cadastrar();
        String sql = "INSERT INTO e4_ocorrencias(ID, DATA, LOCAL, DESCRICAO) "
                + "VALUES (?,?,?,?)";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtID.getText());
            pst.setString(2, txtData.getText());
            pst.setString(3, txtLocal.getText());
            pst.setString(4, txtDescr.getText());
            //System.out.println(pst);

            int resultado = pst.executeUpdate();
            if (resultado == 1) {
                JOptionPane.showMessageDialog(null, "Cadastrado!");

                txtID.setText(null);
                txtData.setText(null);
                txtLocal.setText(null);
                txtDescr.setText(null);

            } else {
                JOptionPane.showMessageDialog(null, "Não Cadastrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnOcoCadActionPerformed

    private void btnOcoPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoPesActionPerformed
        // TODO add your handling code here:
        consultar();
        String sql = "SELECT * FROM e4_ocorrencias WHERE ID=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtID.getText());

            rs = pst.executeQuery();

            if (rs.next()) {
                txtData.setText(rs.getString("Data"));
                txtLocal.setText(rs.getString("Local"));
                txtDescr.setText(rs.getString("Descricao"));

            } else {
                JOptionPane.showMessageDialog(null, "Não Localizado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnOcoPesActionPerformed

    private void btnOcoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoEditActionPerformed
        // TODO add your handling code here:
        atualizar();
        String sql = "UPDATE e4_ocorrencias SET DATA=?, LOCAL=?, DESCRICAO=? WHERE ID=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtData.getText());
            pst.setString(2, txtLocal.getText());
            pst.setString(3, txtDescr.getText());
            System.out.println(pst);

            int atualizado = pst.executeUpdate();
            if (atualizado == 1) {

                JOptionPane.showMessageDialog(null, "Atualizado!");
                txtID.setText(null);
                txtData.setText(null);
                txtLocal.setText(null);
                txtDescr.setText(null);

            } else {
                JOptionPane.showMessageDialog(null, "Não Atualizado!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnOcoEditActionPerformed

    private void btnOcoExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoExcActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_btnOcoExcActionPerformed

    private void btnRelOcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelOcoActionPerformed
        // TODO add your handling code here:
        RelOcorrencia();
    }//GEN-LAST:event_btnRelOcoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOcoCad;
    private javax.swing.JButton btnOcoEdit;
    private javax.swing.JButton btnOcoExc;
    private javax.swing.JButton btnOcoPes;
    private javax.swing.JButton btnRelOco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDescr;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLocal;
    // End of variables declaration//GEN-END:variables

      private void cadastrar() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        String sql = "INSERT INTO e4_ocorrencias (ID, DATA, LOCAL, DESCRICAO) "
                + "VALUES (?,?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtID.getText());
            pst.setString(2, txtData.getText());
            pst.setString(3, txtLocal.getText());
            pst.setString(4, txtDescr.getText());
            
            //System.out.println(pst);

            int resultado = pst.executeUpdate();
            if (resultado == 1) {
                JOptionPane.showMessageDialog(null, "ocorrência cadastrado!!!");
                
            txtID.setText("");
            txtData.setText(null);
            txtLocal.setText("");
            txtDescr.setText("");

            
            } else {
                JOptionPane.showMessageDialog(null, "ocorrência Não cadastrado!!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void consultar() {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void atualizar() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void remover() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja remover?", "ATENÇÃO!!!", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_NO_OPTION) {
            String sql = "delete from e4_ocorrencias where id=?";

            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtID.getText());
                int apagado = pst.executeUpdate();
                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Removido com sucesso!!!");
                    txtID.setText(null);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }

    private void RelOcorrencia() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão", "", JOptionPane.YES_NO_OPTION);
        String caminho = "RelOco1.jasper";
        if (confirma == JOptionPane.YES_NO_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport(caminho, null, conexao);
                JasperViewer.viewReport(print, false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }
}
